### ISSUE TITLE
Certain string sequences are being interpreted as phone numbers

### ISSUE THREAD

**Issue by Mrnofish** [dessalines/rank-my-favs#110]
### Steps to reproduce

1. Create a new item
2. Set the description to something like `Rank my favs is my #1 2024-09-05 8AM #1`

### Expected behavior

The description should show as regular text in matches.

### Actual behavior

The part between underscores is interpreted as a phone number:

`Rank my favs is my #_1 2024-09-05 8_AM #1`

Tapping on it will open the Phone app.

### version of the program

0.3.3

### Android version

Android 13

### Device

guacamole

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/rank-my-favs/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/rankmyfavs](https://lemmy.ml/c/rankmyfavs)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
That's handled the markdown library we're using, https://github.com/jeziellago/compose-markdown . You'll need to open up an issue over there.

**Comment by Mrnofish** [comment]
Sorry, but I am not a user of the library: the app is.

Predictably, I don't have a clue why the app is using it or what's doing with it, any attempt to start a conversation with upstream would be surely very fun to look at, but hardly very productive.
