### ISSUE TITLE
Check to make sure an entry isn't an empty string.

### ISSUE THREAD

**Issue by Mrnofish** [dessalines/rank-my-favs#111]
### Steps to reproduce

1. Import a list of Song Titles, prepending each with a dash, in the Description place the Album Title followed by the track number.
2. Start ranking

### Expected behavior

All matches should display both the contenders.

### Actual behavior

In a quite a fair number of matches, only one contender is shown.

### version of the program

0.3.3

### Android version

Android 13

### Device

guacamole

### Other details

At first I thought this may be related to the length or content of the strings, but it's weird.

It seems sometimes the two contenders are arrayed vertically, one above and the other below, and other times they're laid out horizontally, next to each other.

Perhaps the problem is the app sometimes tries to place them side-to-side even though there's not enough room on the screen to fit both items?

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/rank-my-favs/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/rankmyfavs](https://lemmy.ml/c/rankmyfavs)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
Yes, it uses a flowrow to smartly push any that are too long to the next line. Could you show a picture, or show me how to replicate where its hiding one?

**Comment by Mrnofish** [comment]
After exporting a CSV, I noticed there was an entry with no name/description attached, which somehow squirreled its way among the valid entries, and was likely responsible for the behavior.

I guess it wouldn't be a bad idea to have some checks to warn the user for such an occurrence, especially as the app can import potentially large, machine-generated lists.

Gonna close for the time being.

**Comment by dessalines** [comment]
This is a bug then, we could add a check to remove or make sure no empty entries are added.
