### ISSUE TITLE
Allow ties

### ISSUE THREAD

**Issue by Eloitor** [dessalines/rank-my-favs#112]
### Describe your suggested feature

Sometimes there isn't a clear winner between two options, and a tie is better than randomly picking one or the other or skipping it.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/rank-my-favs/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/rankmyfavs](https://lemmy.ml/c/rankmyfavs)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
The library we use does have a draw option, but I'm not really sure how that would functionally be different from skip.

**Comment by Eloitor** [comment]
Using "skip" you can end up in an infinite loop. Moreover a draw can modify the ratings: in a draw between a very good player and a very bad one, the good player should loose some rating points and the bad one should gain some.

**Comment by dessalines** [comment]
Gotcha. In that case, I'll remove skip and change it to tie / Not sure, and change the logic to make that a glicko draw.

Which language do you think would be best: Tie, Draw, or Not Sure

**Comment by Eloitor** [comment]
I'm not sure, maybe "Tie".
