### ISSUE TITLE
Add Openskill rating system by choice

### ISSUE THREAD

**Issue by Akamar** [dessalines/rank-my-favs#133]
### Describe your suggested feature

You may know about TrueSkill rating system, which is excellent by its design (although more complex than Glicko). The accuracy of winning chances prediction is about 90%, and it can doing matches NxN, rather than just 1x1. Moreover, its rating scale uses real numbers from 0 to 50 and can be easily adapted for rating with "stars" on recommendation services.

There is a FOSS analog of the system, named Openskill, and it's also way faster. We have a Kotlin implementation of this algorithm:

https://github.com/brezinajn/openskill.kt

How about adding this into the app? It also will be useful if you want to use Rank-My-Favs as a sport ranker/predictor someday. User can be able to switch between rating systems to achieve a best outcomes for him personally.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/rank-my-favs/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/rankmyfavs](https://lemmy.ml/c/rankmyfavs)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
I wouldn't be opposed, but this would require a lot of work, and I'm not sure what it improves on over glicko2. So I probably won't do it, but someone else could.

**Comment by dessalines** [comment]
Will re-open and assign it if anyone wants to work on this.
