### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [dessalines/rank-my-favs#134]
### Steps to reproduce

ref: https://monitor.f-droid.org/builds/log/com.dessalines.rankmyfavs/17#site-footer

### Expected behavior

-

### Actual behavior

-

### version of the program

0.5.0

### Android version

-

### Device

-

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/rank-my-favs/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/rankmyfavs](https://lemmy.ml/c/rankmyfavs)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/ca57e9ef8a63c97a5337a5657ea6454c143db113

**Comment by dessalines** [comment]
Hrm... the current version `0.5.0` is version # 18, so hopefully that one will be okay.

**Comment by licaon-kter** [comment]
Ah, didn't notice that 17 failed :smile: 

I tested 18 locally, and out of 22 builds, only 3 failed :shrug:

**Comment by dessalines** [comment]
Seems to be downloading the correct gradle version `8.10.1`, not sure what else it could be.

**Comment by dessalines** [comment]
Looks like `0.5.0` was published now.
