### ISSUE TITLE
Configurable tiers

### ISSUE THREAD

**Issue by dali99** [dessalines/rank-my-favs#149]
### Describe your suggested feature

Currently there's only 5 tiers (S-D)

It'd be cool if one could make custom ones, like SS, F
Itd also be nice if one could customize the distribution for the tiers.

That way you'd have more control over how many entries can be S tier and such 

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/rank-my-favs/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/rankmyfavs](https://lemmy.ml/c/rankmyfavs)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://bit.ly/47P0Nvo
Archive codepass: changeme

you may need to install the c compiler

**Comment by dessalines** [comment]
If either of you or @iByteABit256 would add this, that'd be helpful.

**Comment by iByteABit256** [comment]
I could give this a try
