### ISSUE TITLE
Page/state management weird when going 'back'

### ISSUE THREAD

**Issue by Skivling** [dessalines/rank-my-favs#43]
### Steps to reproduce

After using the app for a while, ranking some, adding more to list, ranking some more, the back button starts not behaving as expected. 

### Expected behavior

The back button should only go to the list, then back to the main menu.

### Actual behavior

All the page switches are stored in the cache, so the back button goes to the rank page, then list, then rank, then list, etc. Which gets really annoying as it's the only way to get back to the main screen.

### version of the program

0.0.4

### Android version

Android 13

### Device

Samsung Galaxy A12

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/rank-my-favs/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/rankmyfavs](https://lemmy.ml/c/rankmyfavs)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
You'll need to be specific about which screens you went to in what order, where the back button isn't navigating to a place that makes sense.

**Comment by dessalines** [comment]
I believe this is fixed now.
