### ISSUE TITLE
Reorder lists on main menu

### ISSUE THREAD

**Issue by Skivling** [dessalines/rank-my-favs#44]
### Describe your suggested feature

One should be able to change the order in which lists are displayed on the main menu.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/rank-my-favs/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/rankmyfavs](https://lemmy.ml/c/rankmyfavs)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
This isn't a priority for me, but if you want to work on it, I'll re-open.

**Comment by dessalines** [comment]
Yes I could sort them alphabetically, rather than by creation time. I suppose that makes more sense.
