### ISSUE TITLE
List icons

### ISSUE THREAD

**Issue by Skivling** [dessalines/rank-my-favs#47]
### Describe your suggested feature

Similar to #44 and #45 in that it's related to how the lists are shown on the main menu.
This would display a custom icon on the left of the list title, if there isn't one it would be as it is now. I believe there are pick-an-icon widgets which can be used.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/rank-my-favs/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/rankmyfavs](https://lemmy.ml/c/rankmyfavs)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
Probably not anything I care to add / support, but I'll re-open should you want to work on it.
