### ISSUE TITLE
Display rank positions for items

### ISSUE THREAD

**Issue by yetanotherfossman** [dessalines/rank-my-favs#59]
### Describe your suggested feature

Currently, ranked items don't have a number before them, so it's easy to get lost in big lists. Also, having numbers would allow to quickly see which are the X best items without having to count them every time.

### Other details

Something like this:

```
1. First item        SCORE
2. Second item       SCORE
3. Third item        SCORE
```

Could be behind a setting if you like how it looks right now.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/rank-my-favs/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/rankmyfavs](https://lemmy.ml/c/rankmyfavs)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
Makes sense.

**Comment by yetanotherfossman** [comment]
Well, the scores there can be useful sometimes to compare how better some items are relative to others. But on the other hand screen space is precious, and relative ranks are indeed more important. So, I'd say add the scores only if there's enough room and you think it makes sense.

**Comment by dessalines** [comment]
Agree, the relative ranks are far more important. I also think removing the score is best to prevent information overload.
