### ISSUE TITLE
Support for descriptions in Import List

### ISSUE THREAD

**Issue by aughts** [dessalines/rank-my-favs#67]
### Describe your suggested feature

It would be convenient to be able to include the description alongside a new entry at the time of import. There would need to be some manner of divider between the entry and description. This could potentially be a character of your choosing, which would necessarily limit that character's use elsewhere in the import. An example import could look like the following:

```
Network (1976) | Not since the dawn of time has America experienced a man like Howard Beale!
Lone Star (1996) | John Sayles invites you to return to the scene of the crime.
The Devils (1971) | Hell holds no surprises for them.
The Seventh Seal (1957) | Most people think neither of death nor loneliness.
```

The | character being used as the divider between a movie and its tagline. The spaces adjacent to the character would not be required.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/rank-my-favs/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/rankmyfavs](https://lemmy.ml/c/rankmyfavs)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
This is a good idea. The description field can be markdown, so this would only be able to support single-line markdown, but it should work.

As far as a delimiter, I spose `|` would be fine.
