### ISSUE TITLE
Sync with local file(s)

### ISSUE THREAD

**Issue by dcdom2** [dessalines/rank-my-favs#77]
### Describe your suggested feature

Neat app idea and nice implementation.

Please let the app write and read to a local file (preferably text for each list). This can be done using SAF so no need for storage permission.

This allows many good things like sync, backup and restore, versioning, and editing on other systems, etc

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/rank-my-favs/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/rankmyfavs](https://lemmy.ml/c/rankmyfavs)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
Not something I'm going to add, as this relies on an internal SQLite DB.

I already have exporting / importing items, and will eventually do that for the entire DB#40 , but not move its DB to local files.

**Comment by dcdom2** [comment]
OK
