### ISSUE TITLE
Items with long titles are stacked vertically when rating

### ISSUE THREAD

**Issue by dcdom2** [dessalines/rank-my-favs#81]
### Steps to reproduce

`A looooooooooong tiiiiiiiiiiiiiiiiiiitle 123`
`A secooooooooooond looooooooooong tiiiiiiiiiiiiiiiiiiitle 456`

### Expected behavior

Word wrapped at half screen width (like a two-column table)

### Actual behavior

Stacked vertically

### version of the program

0.3.1

### Android version

Android 14

### Device

.

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/rank-my-favs/releases/latest)**.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/rankmyfavs](https://lemmy.ml/c/rankmyfavs)
- [X] This is a **single** bug report, in case of multiple bugs I will open  a separate issue for each one  (they can always link to each other if related)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
That's intentional, its using flowrow. If it can't fit them side-by-side comfortably, it smartly stacks them.

**Comment by dcdom2** [comment]
Can I suggest a small tweak to improve UX? Adding some space between them. They are too close for safe tapping.

Thanks
